name: diu_routine_scraper
description: DIU Routine Scraper Flutter Web App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.14.0
  pdf: ^3.10.1
  printing: ^5.11.0
  file_picker: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true