name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.19.0' # Use a stable version

      - name: Initialize Flutter Project
        run: |
          cd frontend
          flutter create .
          flutter pub get

      - name: Build Web
        run: |
          cd frontend
          flutter build web --release --base-href "/diu_routine_scraper/"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build/web
